Global:
  debug: false
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/example1/models/det
  save_epoch_step: 50
  eval_batch_step:
  - 0
  - 50
  cal_metric_during_train: false
  pretrained_model: https://paddleocr.bj.bcebos.com/pretrained/MobileNetV3_large_x0_5_pretrained.pdparams
  # pretrained_model: ./output/ch_PP-OCR_V3_det_recall_smaller_text/best_accuracy
  # pretrained_model: ./output/ch_PP-OCR_V3_det_29_10/best_accuracy
  save_inference_dir: null
  use_visualdl: false
  infer_img: C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/example1
  save_res_path: C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/example1/results/predicts_sast.txt
  distributed: true

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 2    # Reduce the impact of false positives
  beta: 15    # Heavily penalize false negatives
  ohem_ratio: 3
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    # learning_rate: 0.0005
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.4
  max_candidates: 1000
  unclip_ratio: 1.6
  use_dilation: true
Metric:
  name: DetMetric
  main_indicator: recall
Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/
    label_file_list:
      - C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/example1/Label_examples.txt
    # ratio_list: [1]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        # - type: Affine
        #   args:
        #     rotate:
        #     - -10
        #     - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 960
        - 960
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 6
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/
    label_file_list:
      - C:/Users/Leonard/Documents/Python_projects/OCR_new/Raw_Images/example1/Label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 1
